services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`enjoeneer.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.services.portfolio.loadbalancer.server.port=5173"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
