export const metadata = {
  title: 'Hoops vs Beans',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{background: 'linear-gradient(to right, #F9A812 30%, #0095A3 70%)'}}>{children}</body>
    </html>
  )
}
